# Generated by Django 6.0.4 on 2026-06-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_activity_met_value_alter_activity_name_activitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Gym', 'Gym')], default='Cardio', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_muscle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='weight_lifted_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
